CREATE DATABASE IF NOT EXISTS NETWORK_MONITOR;

CREATE TABLE IF NOT EXISTS NETWORK_MONITOR.HOST_CATEGORIES (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(255) NOT NULL,
    SIDE VARCHAR(10) NOT NULL,
    NUM_SEQUENCE TINYINT
);

CREATE TABLE IF NOT EXISTS NETWORK_MONITOR.HOSTS (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    HOST VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    TIME_INTERVAL SMALLINT NOT NULL,
    TIME_UNIT ENUM("1", "60", "3600") NOT NULL,
    MAX_ATTEMPTS TINYINT NOT NULL DEFAULT 2,
    CATEGORY_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(CATEGORY_ID) REFERENCES NETWORK_MONITOR.HOST_CATEGORIES(ID)
);